### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by ThomasThelen** [jostbr/MazeGenerator#3]

**Comment by jostbr** [comment]
Thank you for your contribution on the Cell tests. Appreciate it! And merged it now.

Also on a nother note: While I appreciate your effort, I will be very busy the next month or so, so I won't be able to work anymore on this repository until around christmas. Thta means I won't be able to add updates or respond that much.

**Comment by ThomasThelen** [comment]
Great thanks! I'll try and get the Maze class ones in ASAP. That's totally fine-it looks like your in school too so take your time! You'll see some pull requests here and there, just feel free to reject them if you had something different in mind!

**Comment by ThomasThelen** [comment]
The last of the unit tests will be in the next pull request. Note that it isn't full coverage-I was holding off on testing the `maze` class before refactoring.
