### ISSUE TITLE
Add Support for Code Climate and Travis

### ISSUE THREAD

**Issue by ThomasThelen** [jostbr/MazeGenerator#4]
It would be nice if we could display the current state of the build/unit tests with [Coveralls](https://github.com/coveralls-clients/coveralls-python)

**Comment by jostbr** [comment]
If I change the repo name and then enter the new name on travis-ci.org; is that OK?

**Comment by jostbr** [comment]
I think this (both travis and codeclimate) should be taken care of now. I'm not familiar with these things so if something is not taken care of, just let me know.
